#!/bin/bash
#SBATCH --time=14:00:00
#SBATCH --partition=main 
#SBATCH --output=         ADD FILENAME
#SBATCH --nodes=4
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=200GB         

# Exit immediately if a command exits with a non-zero status
set -e

module purge
module load gcc/11.3.0 openblas/0.3.21 openmpi/4.1.4

export OMP_NUM_THREADS=1

srun -n $SLURM_NTASKS /spack/generic/palace/palace/build/bin/palace cavity_eigenmode12.json